CREATE TABLE BPM_DIM_DATE (
    DATE_KEY NUMBER(10) PRIMARY KEY,
    CALENDAR_DATE DATE,
    YEAR_NUMBER NUMBER(10),
    QUARTER_NUMBER NUMBER(10),
    MONTH_NUMBER NUMBER(10),
    DAY_NUMBER NUMBER(10),
    WEEK_OF_YEAR NUMBER(10),
    DAY_OF_WEEK NUMBER(10),
    WEEKEND NUMBER(1)
);

CREATE TABLE BPM_DIM_PROCESS_DEF (
    PROCESS_KEY VARCHAR2(32) PRIMARY KEY,
    DEFINITION_ID VARCHAR2(255),
    DEFINITION_VERSION_ID VARCHAR2(255),
    DEFINITION_NAME VARCHAR2(255),
    DEFINITION_PATH VARCHAR2(255)
);

CREATE TABLE BPM_DIM_ACTIVITY (
    ACTIVITY_KEY VARCHAR2(32) PRIMARY KEY,
    PROCESS_KEY VARCHAR2(32),
    TRACING_TAG VARCHAR2(255),
    ABSOLUTE_TRACING_TAG VARCHAR2(255),
    ACTIVITY_NAME VARCHAR2(255),
    ACTIVITY_TYPE VARCHAR2(255),
    TOOL VARCHAR2(255)
);

CREATE TABLE BPM_DIM_ACTOR (
    ACTOR_KEY VARCHAR2(32) PRIMARY KEY,
    ENDPOINT VARCHAR2(255),
    RESOURCE_NAME VARCHAR2(255),
    GROUP_CODE VARCHAR2(255),
    ROLE_NAME VARCHAR2(255)
);

CREATE TABLE BPM_FACT_PROC_INST (
    PROCESS_INSTANCE_ID NUMBER(19) PRIMARY KEY,
    ROOT_PROCESS_INSTANCE_ID NUMBER(19),
    PROCESS_KEY VARCHAR2(32),
    START_DATE_KEY NUMBER(10),
    END_DATE_KEY NUMBER(10),
    STARTED_AT TIMESTAMP,
    FINISHED_AT TIMESTAMP,
    DURATION_SECONDS NUMBER(19),
    STATUS VARCHAR2(255),
    DELETED NUMBER(1),
    SUBPROCESS NUMBER(1),
    EVENT_HANDLER NUMBER(1),
    INITIATOR VARCHAR2(255),
    INITIATOR_GROUP_CODE VARCHAR2(255),
    TOTAL_TASK_COUNT NUMBER(10),
    COMPLETED_TASK_COUNT NUMBER(10),
    ACTIVE_TASK_COUNT NUMBER(10),
    CANCELLED_TASK_COUNT NUMBER(10),
    HUMAN_TASK_COUNT NUMBER(10),
    AUTOMATED_TASK_COUNT NUMBER(10),
    REWORK_TASK_COUNT NUMBER(10),
    SOURCE_UPDATED_AT TIMESTAMP
);

CREATE TABLE BPM_FACT_TASK (
    TASK_ID NUMBER(19) PRIMARY KEY,
    PROCESS_INSTANCE_ID NUMBER(19),
    ROOT_PROCESS_INSTANCE_ID NUMBER(19),
    PROCESS_KEY VARCHAR2(32),
    ACTIVITY_KEY VARCHAR2(32),
    ACTOR_KEY VARCHAR2(32),
    START_DATE_KEY NUMBER(10),
    END_DATE_KEY NUMBER(10),
    STARTED_AT TIMESTAMP,
    FINISHED_AT TIMESTAMP,
    DURATION_SECONDS NUMBER(19),
    WAIT_FROM_PREVIOUS_SECONDS NUMBER(19),
    LEAD_FROM_PROCESS_SECONDS NUMBER(19),
    STATUS VARCHAR2(255),
    DECISION VARCHAR2(255),
    DECISION_REASON CLOB,
    PRIORITY NUMBER(10),
    DELEGATED NUMBER(1),
    HUMAN_TASK NUMBER(1),
    AUTOMATED_TASK NUMBER(1),
    REWORK_TASK NUMBER(1),
    SOURCE_UPDATED_AT TIMESTAMP
);

CREATE INDEX IDX_FACT_PROC_DEF ON BPM_FACT_PROC_INST(PROCESS_KEY);
CREATE INDEX IDX_FACT_PROC_STARTED ON BPM_FACT_PROC_INST(STARTED_AT);
CREATE INDEX IDX_FACT_TASK_INST ON BPM_FACT_TASK(PROCESS_INSTANCE_ID);
CREATE INDEX IDX_FACT_TASK_ACTIVITY ON BPM_FACT_TASK(ACTIVITY_KEY);
CREATE INDEX IDX_FACT_TASK_ACTOR ON BPM_FACT_TASK(ACTOR_KEY);
CREATE INDEX IDX_FACT_TASK_STARTED ON BPM_FACT_TASK(STARTED_AT);
