DECLARE
  constraint_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO constraint_count FROM USER_CONSTRAINTS
  WHERE TABLE_NAME = 'BPM_EVENT_INBOX' AND CONSTRAINT_NAME = 'UK_INBOX_CORR_EVENT';
  IF constraint_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BPM_EVENT_INBOX DROP CONSTRAINT UK_INBOX_CORR_EVENT';
  END IF;
END;
/
