server {
    listen 8082;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /admin/;
    }

    location /admin/ {
        try_files $uri/index.html $uri /admin/index.html;
    }

    location /analytics-api/ {
        rewrite ^/analytics-api/(.*)$ /$1 break;
        proxy_pass http://analytics:9095;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
